### PR TITLE
ED - my first PR for lesson7

### PR DESCRIPTION
**Pull request by Edemina**
@nsofiia  please review
@OlgaCasian please review

### CODE REVIEW

**Review by anne2900 — APPROVED** [review]
Nice!

**Comment by DimonKolot** [comment]
looks good

**Review by EllieSky — APPROVED** [review]
Niiiiice!!!!   🚀

**Review by AidaNewQA — APPROVED** [review]
!!!

**Review by nsofiia — APPROVED** [review]
Nice work!🎉

**Pull request closed without merging**
